kind: pipeline
type: docker
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: phpstan
  image: php:8.1
  depends_on:
  - install
  commands:
  - vendor/bin/phpstan analyse

- name: rector
  image: php:8.1
  depends_on:
    - install
  commands:
    - vendor/bin/rector process --dry-run

- name: phpunit
  image: php:8.1
  depends_on:
  - install
  commands:
  - vendor/bin/phpunit

- name: style check
  image: php:8.1
  depends_on:
  - install
  commands:
  - vendor/bin/php-cs-fixer fix
