#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use NunoMaduro\Collision\Provider as CollisionProvider;
use Symfony\Component\Console\Application;
use trizz\AdventOfCode\Commands\ExecuteDay;
use trizz\AdventOfCode\Commands\Puzzle;

(new CollisionProvider())->register();

$application = new Application('Advent of Code by trizz');

$application->add(new Puzzle());
$application->add(new ExecuteDay());

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();
}
