#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use NunoMaduro\Collision\Provider as CollisionProvider;
use Symfony\Component\Console\Application;
use trizz\AdventOfCode\ExecuteDay;
use trizz\AdventOfCode\Puzzle;

(new CollisionProvider)->register();

$application = new Application();

$application->add(new Puzzle());
$application->add(new ExecuteDay());

$application->run();
