#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use AdventOfCode21\Day1;
use AdventOfCode21\Day2;
use AdventOfCode21\Day3;
use AdventOfCode21\Day4;
use AdventOfCode21\Puzzle;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Puzzle());
$application->add(new Day1());
$application->add(new Day2());
$application->add(new Day3());
$application->add(new Day4());

$application->run();
