# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  check:
    cmds:
      - task: echo_title
        vars: { TITLE: Running php-cs-fixer... }
      - task: style
      - task: echo_title
        vars: { TITLE: Running phpstan... }
      - task: phpstan
      - task: echo_title
        vars: { TITLE: Running rector... }
      - task: rector
      - task: echo_title
        vars: { TITLE: Running pest }
      - task: pest

  style:
    cmds:
      - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer fix
    silent: true

  phpstan:
    cmds:
      - php vendor/bin/phpstan --configuration=./phpstan.neon analyse
    silent: true

  rector:
    cmds:
      - php vendor/bin/rector process
    silent: true

  pest:
    cmds:
      - php vendor/bin/pest
    silent: true

  echo_title:
    silent: true
    cmds:
      - echo ------------------------
      - echo {{.TITLE}}
      - echo ------------------------
