---
name: CI

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer install
        uses: php-actions/composer@v5

      - name: Run PHPUnit tests
        run: composer test

  psalm:
    name: Psalm (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer install
        uses: php-actions/composer@v5

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github
