name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: composer:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install

  phpstan:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: php:8.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PHPStan Analysis
        run: vendor/bin/phpstan analyse

  rector:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: php:8.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Rector Dry Run
        run: vendor/bin/rector process --dry-run

  pest:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: php:8.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Pest Tests
        run: vendor/bin/pest

  style-check:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: php:8.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix
